version: '3.9'

services: 
  web:
    build: ./web
    container_name: agenda_web
    restart: always
    tty: true
    ports: 
      - 4200:4200
    volumes: 
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    networks: 
      - agenda_bridge
    depends_on: 
      - api

  api:
    build: ./backend
    container_name: agenda_api
    restart: always
    tty: true
    networks: 
      - agenda_bridge
    ports: 
      - 3000:3000
      # debugging port
      - 9229:9229
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    # command for starting the app in debugging mode
    command: yarn start:debug:docker
    environment:
      NODE_ENV: development
    depends_on: 
      - db

  db:
    image: mongo:latest
    container_name: agenda_db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: agenda
    networks:
      - agenda_bridge
    
  admin:
    image: mongo-express
    container_name: agenda_db_admin
    networks:
      - agenda_bridge
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_OPTIONS_EDITORTHEME: dracula

networks: 
  agenda_bridge:
    driver: bridge